{
	"_Type": "Action.Type.ODataService.DeleteEntity",
	"ActionResult": {
		"_Name": "Customers_DeleteEntity"
	},
	"OnFailure": "/demoapp/Actions/DeleteCustomerEntityFailureMessage.action",
	"OnSuccess": "/demoapp/Actions/CloseModalPage_Complete.action",
	"Target": {
		"Service": "/demoapp/Services/com_sap_edm_sampleservice_v4.service",
		"EntitySet": "Customers",
		"ReadLink": "{@odata.readLink}"
	}
}